name: e_commerce
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  animations: ^2.0.8
  card_swiper: ^3.0.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.12.1
  cupertino_icons: ^1.0.6
  esys_flutter_share_plus: ^2.2.0
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_storage: ^11.3.0
  fluid_bottom_nav_bar: ^1.4.0
    
  flutter:
    sdk: flutter
    
  flutter_launcher_icons: ^0.13.1
  flutter_map: ^6.1.0
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.5.0
  geolocator: ^10.1.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  iconsax: ^0.0.8
  image_picker: ^1.0.4
  latlng: ^1.0.0
  latlong2: ^0.9.0
  material_text_fields: ^1.0.3
  mocktail_image_network: ^1.0.0
  path_provider: ^2.1.1
  provider: ^6.0.5
  share: ^2.0.4
  url_launcher: ^6.1.14
  user_profile_avatar: ^0.1.2
  uuid: ^4.2.1
  very_good_analysis: ^5.1.0
  whatsapp: ^0.0.1
   
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/2.png
    - assets/images/w.png
  