name: e_commerce
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  animate_do: ^3.1.2
  animations: ^2.0.8
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.12.1
  cupertino_icons: ^1.0.6
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  firebase_storage: ^11.3.0
  fluid_bottom_nav_bar: ^1.4.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  google_sign_in: ^6.1.5
  image_picker: ^1.0.4
  material_text_fields: ^1.0.3
  url_launcher: ^6.1.14
  user_profile_avatar: ^0.1.2
  very_good_analysis: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/